# ============================================
# Horizontal Pod Autoscaler
# ============================================
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ideavest-frontend-hpa
  namespace: ideavest-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ideavest-frontend
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ideavest-backend-hpa
  namespace: ideavest-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ideavest-backend
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
