apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ideavest-app

resources:
  - deployment.yaml
  - backend-deployment.yaml
  - service.yaml
  - secrets.yaml
  - ingress.yaml
  - network-policy.yaml
  - hpa.yaml

commonLabels:
  project: ideavest
  managed-by: argocd

images:
  - name: shadymo/ideavest-frontend
    newTag: IMAGE_TAG
  - name: shadymo/ideavest-backend
    newTag: IMAGE_TAG

replicas:
  - name: ideavest-frontend
    count: 2
  - name: ideavest-backend
    count: 2
