apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: coolad-app

resources:
  - deployment.yaml
  - backend-deployment.yaml
  - service.yaml
  - secrets.yaml
  - ingress.yaml

commonLabels:
  project: coolad
  managed-by: argocd
