apiVersion: v1
kind: Secret
metadata:
  name: ideavest-secrets
  namespace: ideavest-app
type: Opaque
stringData:
  database-url: "sqlserver://ideavest_user:SuperSecret123@ideavest-dev-db.abcd1234.us-east-1.rds.amazonaws.com:1433;database=ideavest"
