apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ideavest-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/shadymh10/IdeaVest-graduation.git
    targetRevision: main
    path: k8s/overlays/dev
    kustomize: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: ideavest-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
