apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: ideavest-app

commonLabels:
  environment: dev

images:
  - name: shadymo/ideavest-frontend
    newTag: IMAGE_TAG
  - name: shadymo/ideavest-backend
    newTag: IMAGE_TAG

replicas:
  - name: ideavest-frontend
    count: 2
  - name: ideavest-backend
    count: 2
