apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: coolad-app

commonLabels:
  environment: dev

images:
  - name: DOCKERHUB_USERNAME/coolad-frontend
    newTag: latest

replicas:
  - name: coolad-frontend
    count: 2
